project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests
networks:
  default:
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}